name: Auto Backup Main Branch

on:
  push:
    branches:
      - main

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Set backup branch name
        id: vars
        run: |
          TIMESTAMP=$(date +"%Y-%m-%d-%H%M")
          echo "BRANCH=backup-$TIMESTAMP" >> $GITHUB_ENV

      - name: Create backup branch and push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout -b $BRANCH
          git push origin $BRANCH
